st_app_home:
    path:      /{page}
    defaults:
        _controller: STAppBundle:Trick:index
        page:        1
    requirements:
        page: \d+
        
st_app_view:
    path:      /trick/{slug}/{page}
    defaults:
        _controller: STAppBundle:Trick:view
        page:        1
    requirements:
        page: \d+

st_app_add:
    path:      /add
    defaults:
        _controller: STAppBundle:Trick:add

st_app_edit:
    path:      /edit/{id}
    defaults:
        _controller: STAppBundle:Trick:edit
    requirements:
        id: \d+

st_app_delete:
    path:      /delete/{id}
    defaults:
        _controller: STAppBundle:Trick:delete
    requirements:
        id: \d+

st_app_edit_picture:
    path:      /editpicture/{id}
    defaults:
        _controller: STAppBundle:Picture:edit
    requirements:
        id: \d+

st_app_delete_picture:
    path:      /deletepicture/{id}
    defaults:
        _controller: STAppBundle:Picture:delete
    requirements:
        id: \d+
        


