st_app:
    resource: "@STAppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: STUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults:
        _controller: STUserBundle:Security:register

register_validation:
    path: /register_validation/{token}
    defaults:
        _controller: STUserBundle:Security:registerValidation

forgot_password:
    path: /forgot_password
    defaults:
        _controller: STUserBundle:Security:forgotPassword

reset_password:
    path: /reset_password/{token}
    defaults:
        _controller: STUserBundle:Security:resetPassword

profile:
    path: /profile
    defaults:
        _controller: STUserBundle:Security:profile