st_app:
    resource: "@STAppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: STUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults:
        _controller: STUserBundle:Security:register