<?php

namespace ST\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getComments($trick_id)
	{
		$query = $this->createQueryBuilder('c')
		->where('c.trick = :trick')
		->setParameter('trick', $trick_id)
		->orderBy('c.date', 'DESC')
		->getQuery();

		return $query->getResult();
	}
}
