<?php

namespace ST\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getComments($trick_id, $page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('c')
			->where('c.trick = :trick')
			->setParameter('trick', $trick_id)
			->orderBy('c.date', 'DESC')
			->getQuery();

		//return $query->getResult();

		$query
	      // On définit le commentaire à partir duquel  commencer la liste
	      ->setFirstResult(($page-1) * $nbPerPage)
	      // Ainsi que le nombre de commentaire à afficher sur une page
	      ->setMaxResults($nbPerPage)
        ;  

        return new Paginator($query, true);
	}
}
